---
name: Build project

on:
  workflow_call:
  
jobs:
  test_ccs_build:
    runs-on: ubuntu-latest
    name: Test palindrome project
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        
      - name: Build project
        run: |
          sudo apt-get install libgtest-dev gcovr libicu-dev valgrind
          pushd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp /usr/src/googletest/googletest/lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          popd
          
          cmake CMakeLists.txt || exit 1
          make || exit 1
          valgrind --leak-check=full --error-exitcode=1 ./tests/Test || exit 1
          gcovr --branches --xml-pretty -r . >> gcovr-report.xml

      - name: Generate coverage report        
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.10
        with:
          reports: '*-report.xml'
          reporttypes: 'HtmlInline'
          targetdir: reports

      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Coverage report'
          path: |
            ./src
            ./includes
            ./tests
            ./reports
